Select * from customer limit 10

-- Q1.What is the total revenue generated by male vs female customers

Select gender,sum(purchase_amount) as  Total_Revenue
from customer
group by gender

-- Q2.Which customers used a discount but still purchase more than the average purchase amount

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' 
AND purchase_amount >= (select avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with highest avg review rating

select item_purchased, Round(avg(review_rating :: numeric),2) as avg_review_rating
from customer
group by item_purchased
order by avg(review_rating) Desc
Limit 5

-- Q4. Compare the avg purchase amount between standard and express shipping
select shipping_type, Round(avg(purchase_amount:: numeric),2) as avg_purchase_amount
from customer
Where shipping_type = 'Standard' OR shipping_type = 'Express'
group by shipping_type


-- Q5. Do sunscribed customers spend more? Compare avg spend and total reveneue between
-- subscibers and non-subscribers

Select subscription_status, Round(avg(purchase_amount),2) as avg_spend ,
sum(purchase_amount) as total_revenue,
count(customer_id) as total_customers
from customer
group by subscription_status

-- Q6. Which 5 products have highest percentage of purchases with discount applied?

select item_purchased,
Round(100* sum(case when discount_applied = 'Yes' THEN 1 ELSE 0 END)/Count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate
Limit 5;

-- Q7. Segemt customers into New, Returning and Loyal based on their total number of previous purchases
-- and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases between 2 AND 10 THEN 'Returning'
	ELSE 'Loyal' END AS customer_segment
From customer	
)

Select customer_segment, Count(customer_id) as Total_customers
from customer_type
group by customer_segment


-- Q8. What are the top 3 most purchased product within each category

with item_count as(
select category,
item_purchased, count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id) DESC) AS item_rank
From customer
Group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
Select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q.10 What is the revenue contribution of each age group
Select age_group, sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc

